spring:
  datasource:
    url: jdbc:h2:mem:storedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/test_data.sql
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.demo.store: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%t] %c{1} - %msg%n"

order:
  expiration-time-minutes: 30  # Order lifetime (minutes)
  check-interval-ms: 10000     # Inspection frequency (milliseconds)